name: trivy-pr-scan 
on:
  push: #get rid of this after testing
  pull_request:
    branches:
      - develop
      - master
      - main 
    types: [ opened, synchronize ]
    paths-ignore:
    - README.md
    - .old_cicd/*
    - .github/*
    - .github/workflows/*
    - LICENSE
    - .gitignore
    - .dockerignore
    - .githooks

jobs:
  trivy-pr-scan:
    uses: pchachicho/renci-github-actions/.github/workflows/trivy-pr-scan.yml@main
    secrets: inherit